{% set name = "opentelemetry-exporter-jaeger-thrift" %}
{% set version = "1.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-exporter-jaeger-thrift-{{ version }}.tar.gz
  sha256: 884e3f67fdd922a30337614d2093ce21031b71bac23f73de1ce178349b542aa5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-sdk ~=1.3
    - python >=3.6
    - thrift >=0.10.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-jaeger-thrift
  summary: Jaeger Thrift Exporter for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
