{% set name = "opentelemetry-exporter-jaeger-thrift" %}
{% set version = "1.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-exporter-jaeger-thrift-{{ version }}.tar.gz

  sha256: 8a87b0e63c62dee13ef9fa9a28ad1ca612e06f29e3fa9266f40d2f4969be3af3
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - hatchling
  run:
    - python >=3.6
    - thrift >=0.10.0
    - opentelemetry-api >=1.3,<2.dev0
    - opentelemetry-sdk >=1.11,<2.dev0
test:
  imports:
    - opentelemetry
  commands:
    - pip check
  requires:
    - pip
about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-jaeger-thrift

  summary: Jaeger Thrift Exporter for OpenTelemetry
  license: Apache-2.0

  license_file: LICENSE
extra:
  recipe-maintainers:
    - mariusvniekerk
